services:
  nestjs:
    container_name: project-backend
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    links:
      - "db:database"
    environment:
      - NODE_ENV=docker
    ports:
      - '3000:3000'
    depends_on: [db]
  db:
    container_name: database
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=game
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: {}